### ISSUE TITLE
[INS-314] Project Archive Master Issue

### ISSUE THREAD

**Issue by lsukova** [TheDataMine/the-examples-book#593]
Encompassing issue to be closed when all projects are transferred over, no actual material to create PR.

- [ ] [INS-311] Project Archive; 19000 F2020 - S2021 Projects to New Book
- [ ] [INS-312] Project Archive; 29000 F2020 - S2021 Projects to New Book
- [ ] [INS-313] Project Archive; 39000 F2020 - S2021 Projects to New Book
